/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/MindHomeModel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../../../MindHomeModel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['Mirror 02']} />
      <mesh geometry={nodes.mesh_0_1.geometry} material={materials.Material2} />
      <mesh geometry={nodes.mesh_0_2.geometry} material={materials['Concrete Block 8x8 Gray']} />
      <mesh geometry={nodes.mesh_0_3.geometry} material={materials['Grass Light Green']} />
      <mesh geometry={nodes.mesh_0_4.geometry} material={materials['[0052_FloralWhite]2']} />
      <mesh geometry={nodes.mesh_0_5.geometry} material={materials.Material14} />
      <mesh geometry={nodes.mesh_0_6.geometry} material={materials.Material18} />
      <mesh geometry={nodes.mesh_0_7.geometry} material={materials.Material1} />
      <mesh geometry={nodes.mesh_0_8.geometry} material={materials.Material16} />
      <mesh geometry={nodes.mesh_0_9.geometry} material={materials.H3713_ST9} />
      <mesh geometry={nodes.mesh_0_10.geometry} material={materials[' Material20 sofa fabric']} />
      <mesh geometry={nodes.mesh_0_11.geometry} material={materials['<0011_Seashell>']} />
      <mesh geometry={nodes.mesh_0_12.geometry} material={materials['[0052_FloralWhite]3']} />
      <mesh geometry={nodes.mesh_0_13.geometry} material={materials['Translucent Glass Blue']} />
      <mesh geometry={nodes.mesh_0_14.geometry} material={materials.Material__3} />
      <mesh geometry={nodes.mesh_0_15.geometry} material={materials['[Polished Concrete Old]2']} />
      <mesh geometry={nodes.mesh_0_16.geometry} material={materials['Translucent Glass Gray']} />
      <mesh geometry={nodes.mesh_0_17.geometry} material={materials['SINNERLIG cropped']} />
      <mesh geometry={nodes.mesh_0_18.geometry} material={materials.Material38} />
      <mesh geometry={nodes.mesh_0_19.geometry} material={materials._2} />
      <mesh geometry={nodes.mesh_0_20.geometry} material={materials.Material40} />
      <mesh geometry={nodes.mesh_0_21.geometry} material={materials.Translucent_Glass_Gray} />
      <mesh geometry={nodes.mesh_0_22.geometry} material={materials.Material31} />
      <mesh geometry={nodes.mesh_0_23.geometry} material={materials.Color_000} />
      <mesh geometry={nodes.mesh_0_24.geometry} material={materials['<Snow>']} />
      <mesh geometry={nodes.mesh_0_25.geometry} material={materials['<Silver>']} />
      <mesh geometry={nodes.mesh_0_26.geometry} material={materials['0117_GhostWhite']} />
      <mesh geometry={nodes.mesh_0_27.geometry} material={materials.Kelly_Fringe_2} />
      <mesh geometry={nodes.mesh_0_28.geometry} material={materials.Kelly_Blanket_Black1} />
      <mesh geometry={nodes.mesh_0_29.geometry} material={materials['Kelly _Blanket_White1']} />
      <mesh geometry={nodes.mesh_0_30.geometry} material={materials.Kelly_Fringe_1} />
      <mesh geometry={nodes.mesh_0_31.geometry} material={materials.Material__1} />
      <mesh geometry={nodes.mesh_0_32.geometry} material={materials.Material__2} />
      <mesh geometry={nodes.mesh_0_33.geometry} material={materials.Kelly_Velvet_Pattern1} />
      <mesh geometry={nodes.mesh_0_34.geometry} material={materials.Kelly_Wood1} />
      <mesh geometry={nodes.mesh_0_35.geometry} material={materials.Kelly_Metal1} />
      <mesh geometry={nodes.mesh_0_36.geometry} material={materials.Kelly_TableTop1} />
      <mesh geometry={nodes.mesh_0_37.geometry} material={materials.Material} />
      <mesh geometry={nodes.mesh_0_38.geometry} material={materials.Kelly_Velvet1} />
      <mesh geometry={nodes.mesh_0_39.geometry} material={materials.grey_cloth} />
      <mesh geometry={nodes.mesh_0_40.geometry} material={materials['Translucent Glass Corrugated']} />
      <mesh geometry={nodes.mesh_0_41.geometry} material={materials['0010_Snow clearcoat']} />
      <mesh geometry={nodes.mesh_0_42.geometry} material={materials['[Metal_Corrogated_Shiny]1']} />
      <mesh geometry={nodes.mesh_0_43.geometry} material={materials['halo-4-cortana-256389']} />
      <mesh geometry={nodes.mesh_0_44.geometry} material={materials['00114842400161____3__600x600']} />
      <mesh geometry={nodes.mesh_0_45.geometry} material={materials['<Gainsboro> GROSS']} />
      <mesh geometry={nodes.mesh_0_46.geometry} material={materials['0086_MediumAquamarine']} />
      <mesh geometry={nodes.mesh_0_47.geometry} material={materials['<Khaki>']} />
      <mesh geometry={nodes.mesh_0_48.geometry} material={materials['<LightGray> ALUMINIUM']} />
      <mesh geometry={nodes.mesh_0_49.geometry} material={materials.Wood_Cherry_Original} />
      <mesh geometry={nodes.mesh_0_50.geometry} material={materials.Color_009} />
      <mesh geometry={nodes.mesh_0_51.geometry} material={materials['<DarkGray>2']} />
      <mesh geometry={nodes.mesh_0_52.geometry} material={materials['<SlateGray>']} />
      <mesh geometry={nodes.mesh_0_53.geometry} material={materials['Wood Veneer 02']} />
      <mesh geometry={nodes.mesh_0_54.geometry} material={materials.Tile_white} />
      <mesh geometry={nodes.mesh_0_55.geometry} material={materials['12_sof021']} />
      <mesh geometry={nodes.mesh_0_56.geometry} material={materials.b113_BS} />
      <mesh geometry={nodes.mesh_0_57.geometry} material={materials['[Translucent_Glass_Gray]2']} />
      <mesh geometry={nodes.mesh_0_58.geometry} material={materials.Material17} />
      <mesh geometry={nodes.mesh_0_59.geometry} material={materials['12_s21']} />
      <mesh geometry={nodes.mesh_0_60.geometry} material={materials.rug_material} />
      <mesh geometry={nodes.mesh_0_61.geometry} material={materials['Material~4']} />
      <mesh geometry={nodes.mesh_0_62.geometry} material={materials['Material~1']} />
      <mesh geometry={nodes.mesh_0_63.geometry} material={materials.Color_C02} />
      <mesh geometry={nodes.mesh_0_64.geometry} material={materials['white pillow']} />
      <mesh geometry={nodes.mesh_0_65.geometry} material={materials.Color_B25} />
      <mesh geometry={nodes.mesh_0_66.geometry} material={materials.Material33} />
      <mesh geometry={nodes.mesh_0_67.geometry} material={materials.Material34} />
      <mesh geometry={nodes.mesh_0_68.geometry} material={materials['0081_CadetBlue']} />
      <mesh geometry={nodes.mesh_0_69.geometry} material={materials['Wood Veneer 01']} />
      <mesh geometry={nodes.mesh_0_70.geometry} material={materials.Stacy_Shoe_Laces_Sole} />
      <mesh geometry={nodes.mesh_0_71.geometry} material={materials['[Aluminum]1']} />
      <mesh geometry={nodes.mesh_0_72.geometry} material={materials['Color M01']} />
      <mesh geometry={nodes.mesh_0_73.geometry} material={materials['Color M05']} />
      <mesh geometry={nodes.mesh_0_74.geometry} material={materials['Metal_Aluminum_Anodized fabric']} />
      <mesh geometry={nodes.mesh_0_75.geometry} material={materials.Sketchy_Lines_Wavy_45_A} />
      <mesh geometry={nodes.mesh_0_76.geometry} material={materials.Sketchy_Siding_Scale} />
      <mesh geometry={nodes.mesh_0_77.geometry} material={materials['138705']} />
      <mesh geometry={nodes.mesh_0_78.geometry} material={materials.Color_A01} />
      <mesh geometry={nodes.mesh_0_79.geometry} material={materials['0038_Orange LIGHT']} />
      <mesh geometry={nodes.mesh_0_80.geometry} material={materials['0136_Charcoal']} />
      <mesh geometry={nodes.mesh_0_81.geometry} material={materials['[0133_Gray]1']} />
      <mesh geometry={nodes.mesh_0_82.geometry} material={materials['0131_Silver']} />
      <mesh geometry={nodes.mesh_0_83.geometry} material={materials['[0134_DimGray]1']} />
      <mesh geometry={nodes.mesh_0_84.geometry} material={materials['Agapan Green']} />
      <mesh geometry={nodes.mesh_0_85.geometry} material={materials['Material1 aluminium']} />
      <mesh geometry={nodes.mesh_0_86.geometry} material={materials.Material70} />
      <mesh geometry={nodes.mesh_0_87.geometry} material={materials.Sophie_Skirt} />
      <mesh geometry={nodes.mesh_0_88.geometry} material={materials['138675']} />
      <mesh geometry={nodes.mesh_0_89.geometry} material={materials.Color_004} />
      <mesh geometry={nodes.mesh_0_90.geometry} material={materials.Color_001} />
      <mesh geometry={nodes.mesh_0_91.geometry} material={materials.keyboard} />
      <mesh geometry={nodes.mesh_0_92.geometry} material={materials['0137_Black']} />
      <mesh geometry={nodes.mesh_0_93.geometry} material={materials['[0052_FloralWhite]1']} />
      <mesh geometry={nodes.mesh_0_94.geometry} material={materials.bois} />
      <mesh geometry={nodes.mesh_0_95.geometry} material={materials.Sophie_Shoes1} />
      <mesh geometry={nodes.mesh_0_96.geometry} material={materials['0105_Navy']} />
      <mesh geometry={nodes.mesh_0_97.geometry} material={materials['0044_DarkGoldenrod']} />
      <mesh geometry={nodes.mesh_0_98.geometry} material={materials['0020_Red']} />
      <mesh geometry={nodes.mesh_0_99.geometry} material={materials['0076_Green']} />
      <mesh geometry={nodes.mesh_0_100.geometry} material={materials['2304x1440']} />
      <mesh geometry={nodes.mesh_0_101.geometry} material={materials['[0128_White]1']} />
      <mesh geometry={nodes.mesh_0_102.geometry} material={materials['[Metal_Corrogated_Shiny]3']} />
      <mesh geometry={nodes.mesh_0_103.geometry} material={materials['0015_Salmon']} />
      <mesh geometry={nodes.mesh_0_104.geometry} material={materials.Material73} />
    </group>
  )
}

useGLTF.preload('../../../MindHomeModel.glb')
